on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
permissions:
  contents: write
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Release.txt
        shell: bash
        run: |
          echo "Release: ${{ github.ref_name }}" > Release.txt
          echo ${{ github.sha }} >> Release.txt

      - name: Prepare Release Chrome
        shell: bash
        run: |
          mkdir -p chrome-release
          cp manifest.chrome.json manifest.json
          cp -r Release.txt LICENSE src images chrome-release/
          zip -r chrome-release-${{ github.ref_name }}.zip chrome-release/
      
      - name: Prepare Release Firefox
        shell: bash
        run: |
          mkdir -p firefox-release
          cp manifest.firefox.json manifest.json
          cp -r Release.txt LICENSE src images firefox-release/
          zip -r firefox-release-${{ github.ref_name }}.zip firefox-release/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Extension Release
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            Release.txt
            chrome-release-${{ github.ref_name }}.zip
            firefox-release-${{ github.ref_name }}.zip