on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Create Release
permissions:
  contents: write
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Release
        shell: bash
        run: |
          echo "Release: ${{ github.ref_name }}" > Release.txt
          echo ${{ github.sha }} >> Release.txt
          mkdir -p release
          cp -r src manifest.json images/icons Release.txt LICENSE release/
          zip -r release.zip release/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Chrome Extension Release
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            Release.txt
            release.zip